### ISSUE TITLE
Inconsistent error on similar ways to achieve json encode

### ISSUE THREAD

**Issue by dimasdanz** [breml/errchkjson#19]
Code sample
```go
type request struct {
  ID string `json:"id"`
}

r := request{ID: "ID"}

body := bytes.NewBuffer(nil)
_ = json.NewEncoder(body).Encode(r) // linter reports error on this line

marshalled, _ := json.Marshal(r) // linter does not report error here
body := bytes.NewBuffer(marshalled)
```
`json.NewEncoder(body).Encode(r)` should not report error. because last 2 lines essentially does the same thing.

**Comment by breml** [comment]
Hi @dimasdanz 

Thanks for your report. Originally, `errchkjson` worked the way you are describing. But in #14 we discussed this issue and we found, that `json.NewEncoder(...).Encode()` has some additional error paths, not related to the json encoding it self, but to the operations on the `io.Writer`. Therefore it is not save to omit the errors in this case.

**Comment by dimasdanz** [comment]
Closing this, as I decided to just use `json.Marshal` whenever possible.
