### ISSUE TITLE
False positive for multiple return values

### ISSUE THREAD

**Issue by twpayne** [breml/errchkjson#5]
Given the following code:

```go
package main

type T struct {
    s string
}

func (t T) MarshalJSON() ([]byte, error) {
    return json.Marshal(t.s)
}
```

`errchkjson` reports the error:

```
t.go:8:5: Error return value of `encoding/json.Marshal` is not checked (errchkjson)
        return json.Marshal(t.s)
```
 
which is a false positive, as it is the caller's responsibility to check the return value from `T.MarshalJSON`.

**Comment by breml** [comment]
@twpayne Thanks for your bug report. In will look into this.

**Comment by breml** [comment]
@twpayne Do you mind to test your use case again with the version from PR #6?

**Comment by twpayne** [comment]
I confirm that #6 fixes the bug, thank you :)
